# Generated by Django 5.2 on 2025-09-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productreview_vendorreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='category_parent',
        ),
    ]
