# Generated by Django 5.2 on 2025-09-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_parent_category_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='listing_status',
        ),
    ]
